# Generated by Django 4.0.4 on 2022-06-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_booksuser_bookfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='book.genre'),
        ),
    ]
